name: Build, Test, and Dockerize Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pybuilder
      - name: Run PyBuilder build
        run: |
          pyb clean install
      - name: Run tests and coverage
        run: |
          python -m coverage run --source=src/main/python -m unittest discover src/unittest/python
          python -m coverage report
      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag Docker image for ECR
        run: |
          docker tag ${{ github.repository }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: flask-mysql-crud-service
          cluster: flask-mysql-crud-cluster
          wait-for-service-stability: true

